/**
 * The product's icon set. One source, one size, one stroke weight.
 *
 * Sizes: 16 inside dense rows and buttons, 18 default, 20 for navigation.
 * Never decorate a label that already reads clearly on its own.
 */
export {
  Archive,
  ArchiveRestore,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Banknote,
  Bell,
  Building2,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Clock,
  Copy,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Gift,
  Globe,
  Image as ImageIcon,
  Info,
  LayoutDashboard,
  LayoutTemplate,
  Link as LinkIcon,
  ListOrdered,
  LogOut,
  Mail,
  MapPin,
  Menu as MenuIcon,
  MessageSquareText,
  MoreHorizontal,
  MoreVertical,
  Pencil,
  Percent,
  Phone,
  Plus,
  QrCode,
  Radio,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Ticket,
  TrendingUp,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  Users,
  Video,
  Vote,
  Wallet,
  X,
} from 'lucide-react';
