'use client';

import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { settingsApi } from '@/lib/api';
import { PageHeader, Panel, SubmitButton, Switch } from '@/components/ui/Primitives';

type Plan = { key: string; name: string; price: string; priceSuffix: string; description: string; featured: boolean; features: string[] };
type Config = { currency: string; plans: Plan[]; sharedFeatures: string[]; customDomainAddon: { enabled: boolean; name: string; price: string; description: string }; customService: { title: string; description: string; contactUrl: string } };
const defaults: Config = { currency:'GHS', plans:[
  {key:'starter',name:'Starter',price:'',priceSuffix:'',description:'The essentials to get your event online.',featured:false,features:['Event website / digital invitation','Online RSVP linked to the invitation page']},
  {key:'gold',name:'Gold',price:'',priceSuffix:'',description:'A complete interactive event experience.',featured:true,features:['Event website / digital invitation','Online RSVP linked to the invitation page','Online gifting','Online photo booth for video, audio, selfies and uploads','Live auto-synced itinerary / order of programme']},
  {key:'platinum',name:'Platinum',price:'',priceSuffix:'',description:'The complete experience with a custom domain included.',featured:false,features:['Event website / digital invitation','Online RSVP linked to the invitation page','Online gifting','Online photo booth for video, audio, selfies and uploads','Live auto-synced itinerary / order of programme','Custom domain included']}
], sharedFeatures:['Automatic SMS and email guest notifications','Mobile-browser ticket / invitation code verification and scanning'], customDomainAddon:{enabled:true,name:'Custom Domain Add-on',price:'',description:'Add a custom domain to Starter or Gold. Platinum already includes a custom domain.'}, customService:{title:'Need something more tailored?',description:'Talk to us about a custom EventPeepo experience built around your event.',contactUrl:'https://eventpeepo.com/#contact'} };

export default function AdminPricingPage(){
  const [config,setConfig]=useState<Config>(defaults); const [saving,setSaving]=useState(false); const [loading,setLoading]=useState(true);
  useEffect(()=>{settingsApi.getPricing().then(r=>{const raw=r.data?.pricingConfigJson;if(raw){try{setConfig({...defaults,...JSON.parse(raw)})}catch{}}}).catch(()=>toast.error('Could not load pricing settings')).finally(()=>setLoading(false));},[]);
  const updatePlan=(index:number, patch:Partial<Plan>)=>setConfig(c=>({...c,plans:c.plans.map((p,i)=>i===index?{...p,...patch}:p)}));
  const save=async()=>{setSaving(true);try{await settingsApi.updatePricing(JSON.stringify(config));toast.success('Pricing page updated');}catch{toast.error('Could not save pricing');}finally{setSaving(false)}};
  if(loading)return <div className="p-6 text-sm text-surface-500">Loading pricing settings…</div>;
  return <div className="space-y-6"><PageHeader title="Pricing" meta="Control the public package prices, feature lists and add-ons without changing code." />
    <Panel><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Currency label</label><input className="input" value={config.currency} onChange={e=>setConfig({...config,currency:e.target.value})} placeholder="GHS"/></div><div className="flex items-end"><a href="/pricing" target="_blank" className="btn-secondary">Open public pricing page ↗</a></div></div></Panel>
    {config.plans.map((plan,index)=><Panel key={plan.key}><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-wider text-surface-500">Package</div><h2 className="text-xl font-bold text-surface-900">{plan.name}</h2></div><Switch label="Mark as popular" checked={plan.featured} onChange={v=>updatePlan(index,{featured:v})}/></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Package name</label><input className="input" value={plan.name} onChange={e=>updatePlan(index,{name:e.target.value})}/></div><div><label className="label">Price</label><input className="input" value={plan.price} onChange={e=>updatePlan(index,{price:e.target.value})} placeholder="e.g. 1,500 — leave blank for Contact us"/></div><div><label className="label">Price suffix</label><input className="input" value={plan.priceSuffix} onChange={e=>updatePlan(index,{priceSuffix:e.target.value})} placeholder="e.g. / event"/></div><div><label className="label">Short description</label><input className="input" value={plan.description} onChange={e=>updatePlan(index,{description:e.target.value})}/></div></div><div className="mt-4"><label className="label">Features <span className="font-normal text-surface-500">— one per line</span></label><textarea className="input min-h-44 font-mono text-sm" value={plan.features.join('\n')} onChange={e=>updatePlan(index,{features:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)})}/></div></Panel>)}
    <Panel><h2 className="text-lg font-bold">Features included in every package</h2><p className="mt-1 text-sm text-surface-500">These appear once beneath the package cards.</p><textarea className="input mt-4 min-h-32 font-mono text-sm" value={config.sharedFeatures.join('\n')} onChange={e=>setConfig({...config,sharedFeatures:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)})}/></Panel>
    <Panel><div className="mb-5"><Switch label="Custom domain add-on" description="Allows custom domains to be advertised outside Platinum." checked={config.customDomainAddon.enabled} onChange={v=>setConfig({...config,customDomainAddon:{...config.customDomainAddon,enabled:v}})}/></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Add-on name</label><input className="input" value={config.customDomainAddon.name} onChange={e=>setConfig({...config,customDomainAddon:{...config.customDomainAddon,name:e.target.value}})}/></div><div><label className="label">Add-on price</label><input className="input" value={config.customDomainAddon.price} onChange={e=>setConfig({...config,customDomainAddon:{...config.customDomainAddon,price:e.target.value}})} placeholder="Leave blank for Ask us"/></div></div><div className="mt-4"><label className="label">Description</label><textarea className="input min-h-24" value={config.customDomainAddon.description} onChange={e=>setConfig({...config,customDomainAddon:{...config.customDomainAddon,description:e.target.value}})}/></div></Panel>
    <Panel><h2 className="text-lg font-bold">Custom-tailored service</h2><div className="mt-4 grid gap-4"><div><label className="label">Heading</label><input className="input" value={config.customService.title} onChange={e=>setConfig({...config,customService:{...config.customService,title:e.target.value}})}/></div><div><label className="label">Description</label><textarea className="input min-h-24" value={config.customService.description} onChange={e=>setConfig({...config,customService:{...config.customService,description:e.target.value}})}/></div><div><label className="label">Contact URL</label><input className="input" value={config.customService.contactUrl} onChange={e=>setConfig({...config,customService:{...config.customService,contactUrl:e.target.value}})}/></div></div></Panel>
    <div className="sticky bottom-4 z-20 flex justify-end"><div className="rounded-2xl border border-surface-200 bg-white/95 p-3 shadow-lg backdrop-blur"><SubmitButton loading={saving} onClick={save}>Save pricing</SubmitButton></div></div>
  </div>;
}
